### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'

### ISSUE THREAD

**Issue by Dariushg75** [SlamDevs/slam-mirrorbot#400]
hi,
download is stuck in 100% and show this error in heroku log
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'

**Comment by Placeholder6** [comment]
@Dariushg75 Check your token file

**Comment by Dariushg75** [comment]
hi,
where can i check?
