### ISSUE TITLE
The bot doesn't wake from idled state in reply to bot commands (Heroku)

### ISSUE THREAD

**Issue by Kovinda** [SlamDevs/slam-mirrorbot#408]
**Describe the Bug**
The bot was deployed today. No modifications has been done. 
The bot goes into idle state after 30 mins of inactivity, but doesn't un-idle even after sending bot commands through telegram.
I have to manually restart the dyno through heroku dashboard or I have to ping the app page (appname.herokuapp.com) to un-idle the bot (as i have done in the log)

**Expected behaviour**
The bot is supposed to un-idle after receiving bot commands as it did in the previous versions (before v5.1)

**Screenshots**
Screenshots taken at: 2021-09-13 18:39:58 UTC (8 mins after the bot was idled)
![image](https://user-images.githubusercontent.com/75525796/133139614-df0e7701-02ac-46bc-ada4-4f761194c95a.png)

![image](https://user-images.githubusercontent.com/75525796/133139522-dd3cac10-a2e5-4a5f-a4d1-9fe02b25bca2.png)

**Logs**
[Logfile (gist link)](https://gist.githubusercontent.com/Kovinda/d51b2757affe5131f1b36c42f92dbd9c/raw/1785c9a92d8c6919ffc0bb0db21e19be1c18e4a6/gistfile1.txt)

**Comment by jusidama18** [comment]
Read readme, check all vars description
