### ISSUE TITLE
Please Add branch for deploying to Railway.app

### ISSUE THREAD

**Issue by abhishekhbhootwala** [SlamDevs/slam-mirrorbot#426]
### Is your feature request related to a problem? Please describe.

Please Add branch for deploying to https://railway.app because its not limited like heroku, and also have much bigger space than heroku, (1.03TB free space after bot deployed)

I fork your repo and delete all *.sh file (cause repo detected as bot) and deployed to https://railway.app/ though some error shows but the bot started anyway.

### Describe the solution you'd like

Please Add branch for deploying to Railway.app

**Comment by breakdowns** [comment]
@abhishekhbhootwala No and never
