### ISSUE TITLE
error while using /mirror with mega link

### ISSUE THREAD

**Issue by yunus-25jmi** [SlamDevs/slam-mirrorbot#436]
### Describe the Bug

Heroku log
2021-09-28T15:29:02.951808+00:00 app[web.1]: 2021-09-28 15:29:02,951 - googleapiclient.http - WARNING - Encountered 403 Forbidden with reason "insufficientFilePermissions"

Telegram Log
HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1l_ZR-d_bOgtEN61gKpR_OoVG8CkJpXDT/permissions?supportsTeamDrives=true&alt=json returned "The user does not have sufficient permissions for this file.". Details: "[{'domain': 'global', 'reason': 'insufficientFilePermissions', 'message': 'The user does not have sufficient permissions for this file.'}]"

### Add Logs

HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1l_ZR-d_bOgtEN61gKpR_OoVG8CkJpXDT/permissions?supportsTeamDrives=true&alt=json returned "The user does not have sufficient permissions for this file.". Details: "[{'domain': 'global', 'reason': 'insufficientFilePermissions', 'message': 'The user does not have sufficient permissions for this file.'}]"

### Additional info

Please Look on this bug

**Comment by Placeholder6** [comment]
that file is probably flagged by google, check your drive, see if you can share the file from there, if not then its flagged
